### ISSUE TITLE
Add support for cdk --parameters and --context 

### ISSUE THREAD

**Issue by elgamala** [Biomapas/B.AwsCdkParallel#1]
It would be great if we have the ability to supply --parameter and --context while we are deploying the stacks.

**Comment by laimonassutkus** [comment]
Yeah. Good point. As of now I suggest using OS-level environment variables that are implemented via "env" parameter in DeploymentExecutor.

**Comment by laimonassutkus** [comment]
@elgamala started working on this right now: https://github.com/Biomapas/B.AwsCdkParallel/pull/5/files. Still, a long way to go, but fundamentals are there. Will let you know when finished.

**Comment by laimonassutkus** [comment]
https://github.com/Biomapas/B.AwsCdkParallel/pull/5 merged
