### ISSUE TITLE
Add possibility to specify stacks during deployment

### ISSUE THREAD

**Issue by mokus** [Biomapas/B.AwsCdkParallel#4]
In our app we generate beta and prod stacks together and use `cdk deploy "*-beta"`, and `cdk deploy "*-prod"` respectively

Currently acdk doesn't allow to specify which stacks to deploy

**Comment by laimonassutkus** [comment]
Thanks for the issue. A similar question was already raised and I will work on this feature soon. Probably 2022 Q1.

**Comment by mokus** [comment]
Awesome. Thank you for your work

**Comment by laimonassutkus** [comment]
@mokus actually, started working on this right now: https://github.com/Biomapas/B.AwsCdkParallel/pull/5/files. Still, a long way to go, but fundamentals are there.

**Comment by laimonassutkus** [comment]
https://github.com/Biomapas/B.AwsCdkParallel/pull/5 merged
