### ISSUE TITLE
Could we unpin the CDK version in `setup.py`?

### ISSUE THREAD

**Issue by phitoduck** [Biomapas/B.AwsCdkParallel#7]
Hi there,

Would it be possible to un-fix this dependency in the `setup.py`?

`aws-cdk.core>=1.90.0,<=2.0.0`

I'm hoping to use this for a newer version of CDK.

I realize that `pip install .` can take forever with CDK if you don't pin these. Was the reason you pinned them to make the install go faster? I imagine pinning them may help for ensuring that the tests don't go stale either.

If testing is the reason, one alternative could be to add an extra. Maybe something like:

`pip install .[test]` could cause a particular version range to be fixed--otherwise it would be left loose so this can be install in the same virtual environment as a CDK app using CDK version 2+

Thanks for reading this!

Eric

**Comment by laimonassutkus** [comment]
Hi, you are probably right. There is no real reason for the `core` module to be here. I removed it with the latest commit: https://github.com/Biomapas/B.AwsCdkParallel/commit/13567a5e4c9aa932c83f03d3c0d66f99b0b4e6dc. Now the latest version is `3.2.0`.
